name: Go Docker Container Build

on:
  push:

jobs:
  test:
    name: Go run application local test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
      - name: Cache Go
        id: cache-golang
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: |
            ${{ runner.os }}-go-cache-${{ hashFiles('**/go.*') }}
          restore-keys: |
            ${{ runner.os }}-go-cache-
      - name: Install dependencies
        run: |
          go mod download
          go mod verify
      - name: Build executable
        run: go build -v -o app ./...
      - name: Start the application and stop after few seconds
        run: timeout 3s ./app
  deploy:
    name: Build Container and Docker Run Test
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - name: Init setup
        run: echo "Init setup..."
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        run: docker build -t go-echo .
      - name: Run Docker image
        run: |
          docker run -d --name ci-container -p 1323:1323 go-echo
          sleep 5
          curl http://localhost:1323
          docker stop ci-container
