name: Go Docker Container Build

on:
  push:

jobs:
  build:
    name: Build Container
    runs-on: ubuntu-20.04
    steps:
      - name: Init setup
        run: echo "Init setup..."
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        run: docker build -t go-echo .
      - name: Run Docker image
        run: |
          docker run -d --name ci-container -p 1323:1323 go-echo
          sleep 5
          curl http://localhost:1323
          docker stop ci-container
